language: go

go:
- 1.11.x

go_import_path: github.com/aelsabbahy/goss

sudo: required
dist: trusty

os:
- linux
- windows

services:
- docker

before_install:
- if [ "$TRAVIS_OS_NAME" == "windows" ]; then choco install make; fi
- go get -u golang.org/x/lint/golint

script:
# TODO(ENG-1523): windows does not currently support test-int-*, only unit tests executed from make.
- if [ "$TRAVIS_OS_NAME" == "windows" ]; then make lint test; else make; fi

deploy:
  provider: releases
  api_key:
    secure: fjSvruBkLiuIXxCyomXRAcXjz6i+/sQiNWMrVjq2lICvs8OTXiYnOPtQZDsps8rfZTb4weDUQP8hJjd2IQKefMJuqRi4xcm976PhqFn/hjBJngOvHCrReHrfjuV5McGZlmxxittcvxBNj94hCRcQPL0CM7VFH11Jd/tmavQcpkLqjASwVWEozQjQlXRzWwbHCLt+xy1q/5Ql9+FvNAscQNqsgguUMUpa9D07ofMWBc/0UwEQsSeWOc+KujRXga+bjJvJ+Bg/s0jW9fUSwIwS9u7ib8f46mAZzz+Qwvz1qx5KOzUCUjhBqPz+e5b9i9hRvNHpnaK7wSlpbIurff4/8B6qGTQ/UP0+N0fYgx0vvIhQs976scGglsf2u3Mt3IYUnyG7m9kp28kjBXv3bKJZGGuqec/p37xkUIuNwA7dQepeNB2/d0VZE5M0IgItLHuv4pZNwp6jNVHzLN5lFXiLVpjLqRQYNR1cu9V1ImeKWuHg+sgop4CboBNrzp0hKRiUysqp31EU24s9RxzUZSbXF8lk1dLhLCjzuy0qkjPgGZudkUhXU+d6pZEkIP3Li5mWHJrcRaHSXrPMFfH7JHLHjkEJTRnh4kHdD3u7eAv+B5qIEp9mEweQEBXonjmoZp4jj0MKLrE6j6j/hIJC/HS1omscMQwauAliOGyHtSZTgAw=
  file:
    - release/goss-linux-amd64
    - release/goss-linux-386
    - release/goss-linux-arm
    - release/goss-windows-amd64
    - extras/dgoss/dgoss
  on:
    repo: improbable-eng/goss
    tags: true
