---
language: go

services:
  - docker

matrix:
  include:
    - os: linux
      go: "1.9.x"
      sudo: required
      dist: trusty
    - os: linux
      go: "1.10.x"
      sudo: required
      dist: trusty
    - os: linux
      go: "1.11.x"
      sudo: required
      dist: trusty
    - os: osx
      osx_image: xcode9.4
    - os: windows

before_install:
  - "ci/before_install.${TRAVIS_OS_NAME}.sh"
  - if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then export PATH="$PATH:${PWD}/linux-amd64"  ; fi
  - if [[ "${TRAVIS_OS_NAME}" == "osx"   ]]; then export PATH="$PATH:${PWD}/darwin-amd64" ; fi

script:
  - make deps
  - make

deploy:
  provider: releases
  api_key:
    secure: hEHCC4EN7iHz7pIWKRn2qw22NTqUxnuBp59wfAlLBtV26j5rHMzSu8mlxkJInusDUGLJiNLrZPRWN0mzOdIXalbUeLhlX7EflJgEj6Q0MchUR69LzCAp0KMIFL1Sfq0v81VgujRLUUy5utxDL8Er4tZknn2PpXAMzpO+ozjNRDhhSEM4iMXfY3bcOIMnx6XRgCjFCb036wlBgOfdgv5fwm2PP638DTKar4W6ZZbqCQByhJ5RyL3BMDPTT0moA/tYbG+FA6p6Rme1OcBkMnpsiJZoB3u8gxsNiEJ43/C2RcULW/18qqp2UVD5FipSDYP7GQ5ugKCbgpWXb0Ctl8o4hv1UsNl0XoyJhAt0PRp6vqnyy6LWB2FzX30Xj/vGIhO/IfiJvspHxpatTk7Esjr46K4u9ao/x63LX6F6yI1ZTfbzt2MhRYRjwh4ORNfqhysuzXChftX1S9hj6s6gO0/zqoOsRK/PK8DProbUn4bxrGOBzi16P0GEk4agWWUm74Pis9qCThXNW8MXEV936KvE1wb1RxTACYvFBtO2IM5eQ26t2Y7mGJd7FJup9LR4oUtUTSbYo5P2Sal6xntBKH5P4nwEtM+TtHoeSCKQ3X5i1VSdvAH7soEAly6rP5d5wwPhqqx9mgUPYO/3ulvxLJOYHamrbj6nlHDXnCEoj1ZMxX4=
  file:
    - release/goss-linux-amd64
    - release/goss-linux-386
    - release/goss-linux-arm
    - extras/dgoss/dgoss
  skip_cleanup: true
  on:
    repo: aelsabbahy/goss
    tags: true
